language: scala

scala:
  - 2.13.2

jdk:
  - openjdk8

sudo: false

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_install:
  - "test -z \"$encrypted_3b9f0b9d36d1_key\" || (openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in project/secrets.tar.enc -out project/secrets.tar -d && tar -xf project/secrets.tar -C project)"

stages:
  - name: lint
  - name: test
  - name: publish
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      name: "Check source code formatting"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Build and test for Scala 2.13"
      before_script: gpg --import project/ci.asc
      script: sbt ++$TRAVIS_SCALA_VERSION test package packageSrc publishLocal
    - <<: *test
      scala: 2.12.11
      name: "Build and test for Scala 2.12"
    - &publish
      stage: publish
      name: "Publish"
      before_script: gpg --import project/ci.asc
      script: sbt +publish sonatypeBundleReleaseIfNotSnapshot

env:
  global:
    - secure: "A2lnCKMKjEnoQm1mx5IOqIrspgMw+tDT+MXi2MWw35GP8+y2zZMMoFNOvv+v7o8gqnGqFp6I2DXum050Bc+od/rESgowOp/sY4VuVnOzB1iILG7EeCQmTowsehwnlLnOGHT3NeXEvtaft0HDLGyny4dojdOiCmS1kOghVm/UMJhXGSq2L1qCC+r7+ZXgEhn+bkOOwpb/4jUpkBokmp5xKITwxGUiu+AfoBFqlCdUcMDTRA16schsJASTsXwwsfa88171IMaLCFmAqoiwPDnhyTABhyWkGXemfY1Kdk8vQf8TVFudffQBtNu/sHf9w5qVwQDfmjFRfdBLTAGP4P8csdlv1LFHM8xQZ9aZV7TeysUUGm8GiLeFQep89+dItVPJuJS0Rg2qCjP9gRgoyFl/R712lDJY5km6KIW9uGofCffFyoCu/i4I9QGpy3kjIdzE2RzPfzXgkaP041lpRvyvPE3WjFoblZhwg9zissR2JD9UFV02KIpKEp6PhB5Jgpxt+aaCpwc/bOD7RDQywl2JcsUAzOYQjaBhLtY+D4K4+yUiOs0o48iC0g9QJiBBOkBkOBNskvMMY/70rdwpdxyXPfufbCoLuvc7B+MRLQ/3nmlSGvYebD4TE2Nmrfqp4xhbejt57OCCFUzfNqA7tTD7/H57JaguOKefLRrxRQJkaRw="
    - secure: "T9Bu3KDpqUy2agiyPRQ89uY+wAB4r45Ss7H0hxjzcxJE4PLnAfcAg4+2e4EYNp90sRBhrj3p6w6OuGuFeXwu81+JFzEPjsNZe7k27k1vexJ2w8u9lIpwcH+Y6HWiZnOV85+n3f+PSvQ8SyF1UktuU2iq4D09BdSUnfs9QwatW3HSx7wYrfVCW7+13flURGqNzcoFZhnPmKiC53LoKRdOJpTHfv+TRFw8kTXdPfPcp3gE0oSR9EGfNG+f85zfXsi9v1vfnOVt2bWdjsS0p58TRC9dAtmicNxBNiSV7K49A8+skicrCDxXg4I7U8eD2jmO061+Q82aQAZ9o08EvhC3dZd7uHEt9IMH0crFZ4zB74qDPxZXhBg8yPRuJyYP9PTLlY7nBHbNA0OkF6Y+IesgTsdLB06EFCY7Zc+5IEaJ43tRrbTASY2R1/4nMLbabBsfzHfVdS1XQJ+PJFOSkVp9JKBberLNJjR5WijPv1q6HmribKLmfSPP0G3ohNiwWbJ9W9bI0kg2lZlQnO8GGTUhaiK242V0aEEAR9XWLF624DiOvwyTL2DVm7lcQuRMknglUwY0w8NBG/yXsXFjz2YaqUnTDvEPpP5c+dk5l7AmMnLumRnumXUcM18xsrpp0kGJ1Cp/CCkeW6VYlXZMpalCoIV4kxVpxYSnZPMQ7mETpHk="
